#!/bin/bash -ex

LOCAL=$HOME/.local
NAME=gn
INSTALL=$LOCAL/install/$NAME
BIN=$LOCAL/bin
UNAME=`uname`
CC=`which gcc`
CXX=`which g++`
AR=`which ar`

mkdir -p $BIN
rm -rf $INSTALL && mkdir -p $INSTALL

git clone https://gn.googlesource.com/gn $INSTALL
cd $INSTALL
python build/gen.py
ninja -C out

cp out/gn $BIN
rm -rf $INSTALL

